name: Waypoints
main: com.asylumsw.bukkit.waypoints.Waypoints
version: 2.0
author: Jonathan Borzilleri
description: >
             Provides teleportation services.
commands:
  wp:
    description: Access to all waypoint commands.
    usage: |
           /<command> home activate - Activate your home point.
           /<command> home remove - Remove your home point.
           /<command> home - Teleport to your home point.
           /<command> gate list - List gates you have access to.
           /<command> gate <name> - Travel to the specified gate.
           /<command> gate activate <name> - Activate a gate with the specified name.
           /<command> gate remove - NYI
           /<command> gate check - Check to see if your current location can hold a gate.
           /<command> track <name> - Track the specified point.
           /<command> marker list - List your markers.
           /<command> marker set <name> - Set a marker with the given name.
           /<command> marker remove <name> - Removes a marker.
